name: nordpooldb-env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - sqlalchemy
  - psycopg2-binary
  - pip

  # Anything under “pip:” will be installed via pip into the same env
  - pip:
    - python-dotenv
