name: Check API Alerts

# Schedule: once per day at 09:20 UTC, plus allow manual dispatch
on:
  schedule:
    - cron: '20 9 * * *'
  workflow_dispatch:

jobs:
  notify_if_alerts:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies via pip
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write Google credentials
        run: |
          echo "${{ secrets.GCP_TOKEN_JSON }}" > token.json        

      - name: Run alert checker
        env:
          DB_HOST:     ${{ secrets.DB_HOST }}
          DB_PORT:     ${{ secrets.DB_PORT }}
          DB_NAME:     ${{ secrets.DB_NAME }}
          DB_USER:     ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          SMTP_HOST:     ${{ secrets.SMTP_HOST }}
          SMTP_PORT:     ${{ secrets.SMTP_PORT }}
          SMTP_USER:     ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          EMAIL_FROM:    ${{ secrets.EMAIL_FROM }}
          EMAIL_TO:      ${{ secrets.EMAIL_TO }}
          SPREADSHEET_ID:  ${{ secrets.SPREADSHEET_ID }}

        run: |
          python src/check_alerts.py
